Actividad 5

Importar archivos
Lectura del archivo


**discribe.()

In [36]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [38]:

rd = pd.read_csv("spotify_history.csv")
dtos = pd.DataFrame(rd)

In [39]:
dtos

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,audiobook_title,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,offline,offline_timestamp,incognito_mode
0,2022-12-29T16:39:18Z,android,753,CL,Warning Sign,Coldplay,A Rush of Blood to the Head,spotify:track:4bPkBHKLKd9WHizsvM2zV3,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,fwdbtn,True,False,1672331958,False
1,2022-12-29T16:39:19Z,android,1661,CL,Houdini,Foster The People,Torches,spotify:track:5Fli1xRi01bvCjsZvKWro0,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,fwdbtn,True,False,1672331958,False
2,2022-12-29T16:39:21Z,android,1000,CL,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,spotify:track:3c7N2fCFB4JVKGF8cWfteh,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,fwdbtn,True,False,1672331960,False
3,2022-12-29T16:39:22Z,android,1097,CL,Waves of Nature,WILLOW,ARDIPITHECUS,spotify:track:1zJMFf0EzbGCpL0zROfmVF,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,backbtn,True,False,1672331962,False
4,2022-12-29T16:43:38Z,android,256920,CL,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,spotify:track:3c7N2fCFB4JVKGF8cWfteh,NaN,NaN,...,NaN,NaN,NaN,NaN,backbtn,trackdone,True,False,1672331963,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41822,2025-07-13T15:18:31Z,osx,29642,CL,Flintstones,Jacob Collier,In My Room,spotify:track:731rnSkAluFeKZaGTHig7W,NaN,NaN,...,NaN,NaN,NaN,NaN,clickrow,endplay,True,False,1752419857,False
41823,2025-07-13T15:21:40Z,osx,187573,CL,Moon River,Jacob Collier,Djesse Vol. 2,spotify:track:1IRRqn75jaZHp7zMT1NGbZ,NaN,NaN,...,NaN,NaN,NaN,NaN,playbtn,endplay,True,False,1752419911,False
41824,2025-07-13T15:26:51Z,osx,54677,CL,Moon River,Louis Armstrong,"Hello, Dolly!",spotify:track:17gxfuiFUrLhbUKdunxUPJ,NaN,NaN,...,NaN,NaN,NaN,NaN,playbtn,endplay,True,False,1752420356,False
41825,2025-07-13T15:28:54Z,osx,122345,CL,Moon River,Audrey Hepburn,Fruhstuck Bei Tiffany (Original Soundtrack),spotify:track:7BFkmua2qkqf1nCUHHflaK,NaN,NaN,...,NaN,NaN,NaN,NaN,playbtn,endplay,True,False,1752420412,False
41826,2025-07-15T13:45:38Z,osx,0,CL,Moon River - Alternate Take,Henry Mancini,Mr Lucky,spotify:track:1SD0f3foJvgJbqxiJrz7i6,NaN,NaN,...,NaN,NaN,NaN,NaN,trackdone,remote,True,False,1752420535,False

Limpiar datos:

In [40]:
pd.isna(dtos)
#limpiar  df_reemplazado = df.replace(np.nan, 0)

limpio = dtos["ms_played"].replace(np.nan, 0)
limpio

0           753
1          1661
2          1000
3          1097
4        256920
          ...
41822     29642
41823    187573
41824     54677
41825    122345
41826         0
Name: ms_played, Length: 41827, dtype: int64

In [41]:

dtos.columns
dtos["ts"]

0        2022-12-29T16:39:18Z
1        2022-12-29T16:39:19Z
2        2022-12-29T16:39:21Z
3        2022-12-29T16:39:22Z
4        2022-12-29T16:43:38Z
                 ...
41822    2025-07-13T15:18:31Z
41823    2025-07-13T15:21:40Z
41824    2025-07-13T15:26:51Z
41825    2025-07-13T15:28:54Z
41826    2025-07-15T13:45:38Z
Name: ts, Length: 41827, dtype: object

In [63]:


js = dtos["ms_played"] == limpio

js

0        True
1        True
2        True
3        True
4        True
         ...
41822    True
41823    True
41824    True
41825    True
41826    True
Name: ms_played, Length: 41827, dtype: bool

In [67]:
df = dtos.copy()


df = df.replace('*', np.nan)
df = df.replace('None', np.nan)
df = df.replace(' ', np.nan)
df = df.replace(-999, np.nan)



df

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,audiobook_title,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,offline,offline_timestamp,incognito_mode
0,2022-12-29T16:39:18Z,android,753,CL,Warning Sign,Coldplay,A Rush of Blood to the Head,spotify:track:4bPkBHKLKd9WHizsvM2zV3,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,fwdbtn,True,False,1672331958,False
1,2022-12-29T16:39:19Z,android,1661,CL,Houdini,Foster The People,Torches,spotify:track:5Fli1xRi01bvCjsZvKWro0,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,fwdbtn,True,False,1672331958,False
2,2022-12-29T16:39:21Z,android,1000,CL,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,spotify:track:3c7N2fCFB4JVKGF8cWfteh,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,fwdbtn,True,False,1672331960,False
3,2022-12-29T16:39:22Z,android,1097,CL,Waves of Nature,WILLOW,ARDIPITHECUS,spotify:track:1zJMFf0EzbGCpL0zROfmVF,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,backbtn,True,False,1672331962,False
4,2022-12-29T16:43:38Z,android,256920,CL,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,spotify:track:3c7N2fCFB4JVKGF8cWfteh,NaN,NaN,...,NaN,NaN,NaN,NaN,backbtn,trackdone,True,False,1672331963,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41822,2025-07-13T15:18:31Z,osx,29642,CL,Flintstones,Jacob Collier,In My Room,spotify:track:731rnSkAluFeKZaGTHig7W,NaN,NaN,...,NaN,NaN,NaN,NaN,clickrow,endplay,True,False,1752419857,False
41823,2025-07-13T15:21:40Z,osx,187573,CL,Moon River,Jacob Collier,Djesse Vol. 2,spotify:track:1IRRqn75jaZHp7zMT1NGbZ,NaN,NaN,...,NaN,NaN,NaN,NaN,playbtn,endplay,True,False,1752419911,False
41824,2025-07-13T15:26:51Z,osx,54677,CL,Moon River,Louis Armstrong,"Hello, Dolly!",spotify:track:17gxfuiFUrLhbUKdunxUPJ,NaN,NaN,...,NaN,NaN,NaN,NaN,playbtn,endplay,True,False,1752420356,False
41825,2025-07-13T15:28:54Z,osx,122345,CL,Moon River,Audrey Hepburn,Fruhstuck Bei Tiffany (Original Soundtrack),spotify:track:7BFkmua2qkqf1nCUHHflaK,NaN,NaN,...,NaN,NaN,NaN,NaN,playbtn,endplay,True,False,1752420412,False
41826,2025-07-15T13:45:38Z,osx,0,CL,Moon River - Alternate Take,Henry Mancini,Mr Lucky,spotify:track:1SD0f3foJvgJbqxiJrz7i6,NaN,NaN,...,NaN,NaN,NaN,NaN,trackdone,remote,True,False,1752420535,False

In [69]:
df.isna()

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,audiobook_title,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,offline,offline_timestamp,incognito_mode
0,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41822,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,False,False,False,False,False,False
41823,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,False,False,False,False,False,False
41824,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,False,False,False,False,False,False
41825,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,False,False,False,False,False,False
41826,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,False,False,False,False,False,False

In [72]:
df.columns
df.dropna(subset=['platform'])

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,audiobook_title,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,offline,offline_timestamp,incognito_mode
0,2022-12-29T16:39:18Z,android,753,CL,Warning Sign,Coldplay,A Rush of Blood to the Head,spotify:track:4bPkBHKLKd9WHizsvM2zV3,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,fwdbtn,True,False,1672331958,False
1,2022-12-29T16:39:19Z,android,1661,CL,Houdini,Foster The People,Torches,spotify:track:5Fli1xRi01bvCjsZvKWro0,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,fwdbtn,True,False,1672331958,False
2,2022-12-29T16:39:21Z,android,1000,CL,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,spotify:track:3c7N2fCFB4JVKGF8cWfteh,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,fwdbtn,True,False,1672331960,False
3,2022-12-29T16:39:22Z,android,1097,CL,Waves of Nature,WILLOW,ARDIPITHECUS,spotify:track:1zJMFf0EzbGCpL0zROfmVF,NaN,NaN,...,NaN,NaN,NaN,NaN,fwdbtn,backbtn,True,False,1672331962,False
4,2022-12-29T16:43:38Z,android,256920,CL,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,spotify:track:3c7N2fCFB4JVKGF8cWfteh,NaN,NaN,...,NaN,NaN,NaN,NaN,backbtn,trackdone,True,False,1672331963,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41822,2025-07-13T15:18:31Z,osx,29642,CL,Flintstones,Jacob Collier,In My Room,spotify:track:731rnSkAluFeKZaGTHig7W,NaN,NaN,...,NaN,NaN,NaN,NaN,clickrow,endplay,True,False,1752419857,False
41823,2025-07-13T15:21:40Z,osx,187573,CL,Moon River,Jacob Collier,Djesse Vol. 2,spotify:track:1IRRqn75jaZHp7zMT1NGbZ,NaN,NaN,...,NaN,NaN,NaN,NaN,playbtn,endplay,True,False,1752419911,False
41824,2025-07-13T15:26:51Z,osx,54677,CL,Moon River,Louis Armstrong,"Hello, Dolly!",spotify:track:17gxfuiFUrLhbUKdunxUPJ,NaN,NaN,...,NaN,NaN,NaN,NaN,playbtn,endplay,True,False,1752420356,False
41825,2025-07-13T15:28:54Z,osx,122345,CL,Moon River,Audrey Hepburn,Fruhstuck Bei Tiffany (Original Soundtrack),spotify:track:7BFkmua2qkqf1nCUHHflaK,NaN,NaN,...,NaN,NaN,NaN,NaN,playbtn,endplay,True,False,1752420412,False
41826,2025-07-15T13:45:38Z,osx,0,CL,Moon River - Alternate Take,Henry Mancini,Mr Lucky,spotify:track:1SD0f3foJvgJbqxiJrz7i6,NaN,NaN,...,NaN,NaN,NaN,NaN,trackdone,remote,True,False,1752420535,False

In [74]:

##df2['col2'] = df2['col2'].fillna(value='d')


df["ms_played"].describe()

count    4.182700e+04
mean     1.899677e+05
std      3.552166e+05
min      0.000000e+00
25%      2.413300e+04
50%      1.673050e+05
75%      2.450990e+05
max      7.932138e+06
Name: ms_played, dtype: float64

In [77]:
nw =df.drop(["audiobook_title","episode_show_name"], axis =1, inplace = True)
nw